version: '3'
networks:
  default:
    external:
      name: base-microservices
services:
  base-local-api:
    image: node:16.14-alpine3.15
    command: yarn dev
    environment:
      PORT: 30001
      GRPC_TRACE: dns_resolver
      GRPC_VERBOSITY: DEBUG
    ports:
      - 30001:30001
    volumes:
      - ./:/source
    working_dir: /source
